package com.yangqisport.web.vo;

import java.util.Date;

public class ActivityVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.ID
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.GMT_MODIFIY
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Date gmtModifiy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.GMT_CREATE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.MODIFIER
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.CREATOR
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.IS_DELETED
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.TYPE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.GMT_BEGIN
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Date gmtBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.LOCATION
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.JOIN_USER_COUNT
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Integer joinUserCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.MAX_JOIN_NUM
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Integer maxJoinNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.COST_TYPE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String costType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.TITLE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.INTRODUCTION
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String introduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.COVER_IMAGES
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String coverImages;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.PUBLISHER_USER_ID
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Long publisherUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.ID
     *
     * @return the value of activity.ID
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.ID
     *
     * @param id the value for activity.ID
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.GMT_MODIFIY
     *
     * @return the value of activity.GMT_MODIFIY
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Date getGmtModifiy() {
        return gmtModifiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.GMT_MODIFIY
     *
     * @param gmtModifiy the value for activity.GMT_MODIFIY
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setGmtModifiy(Date gmtModifiy) {
        this.gmtModifiy = gmtModifiy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.GMT_CREATE
     *
     * @return the value of activity.GMT_CREATE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.GMT_CREATE
     *
     * @param gmtCreate the value for activity.GMT_CREATE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.MODIFIER
     *
     * @return the value of activity.MODIFIER
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.MODIFIER
     *
     * @param modifier the value for activity.MODIFIER
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.CREATOR
     *
     * @return the value of activity.CREATOR
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.CREATOR
     *
     * @param creator the value for activity.CREATOR
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.IS_DELETED
     *
     * @return the value of activity.IS_DELETED
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.IS_DELETED
     *
     * @param isDeleted the value for activity.IS_DELETED
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.TYPE
     *
     * @return the value of activity.TYPE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.TYPE
     *
     * @param type the value for activity.TYPE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.GMT_BEGIN
     *
     * @return the value of activity.GMT_BEGIN
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Date getGmtBegin() {
        return gmtBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.GMT_BEGIN
     *
     * @param gmtBegin the value for activity.GMT_BEGIN
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setGmtBegin(Date gmtBegin) {
        this.gmtBegin = gmtBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.LOCATION
     *
     * @return the value of activity.LOCATION
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.LOCATION
     *
     * @param location the value for activity.LOCATION
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.JOIN_USER_COUNT
     *
     * @return the value of activity.JOIN_USER_COUNT
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Integer getJoinUserCount() {
        return joinUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.JOIN_USER_COUNT
     *
     * @param joinUserCount the value for activity.JOIN_USER_COUNT
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setJoinUserCount(Integer joinUserCount) {
        this.joinUserCount = joinUserCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.MAX_JOIN_NUM
     *
     * @return the value of activity.MAX_JOIN_NUM
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Integer getMaxJoinNum() {
        return maxJoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.MAX_JOIN_NUM
     *
     * @param maxJoinNum the value for activity.MAX_JOIN_NUM
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setMaxJoinNum(Integer maxJoinNum) {
        this.maxJoinNum = maxJoinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.COST_TYPE
     *
     * @return the value of activity.COST_TYPE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getCostType() {
        return costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.COST_TYPE
     *
     * @param costType the value for activity.COST_TYPE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setCostType(String costType) {
        this.costType = costType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.TITLE
     *
     * @return the value of activity.TITLE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.TITLE
     *
     * @param title the value for activity.TITLE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.INTRODUCTION
     *
     * @return the value of activity.INTRODUCTION
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.INTRODUCTION
     *
     * @param introduction the value for activity.INTRODUCTION
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.COVER_IMAGES
     *
     * @return the value of activity.COVER_IMAGES
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getCoverImages() {
        return coverImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.COVER_IMAGES
     *
     * @param coverImages the value for activity.COVER_IMAGES
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setCoverImages(String coverImages) {
        this.coverImages = coverImages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.PUBLISHER_USER_ID
     *
     * @return the value of activity.PUBLISHER_USER_ID
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Long getPublisherUserId() {
        return publisherUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.PUBLISHER_USER_ID
     *
     * @param publisherUserId the value for activity.PUBLISHER_USER_ID
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setPublisherUserId(Long publisherUserId) {
        this.publisherUserId = publisherUserId;
    }
}