package com.yangqisport.web.vo;

import java.util.Date;

public class UserVO {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.ID
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Long   id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.GMT_MODIFIY
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Date   gmtModifiy;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.GMT_CREATE
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Date   gmtCreate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.MODIFIER
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.CREATOR
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.IS_DELETED
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.LOGIN_ID
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.NICKNAME
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.PASSWORD
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.SEX
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.AVATAR
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.INDUSTRY
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.REGION
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.MEMO
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.BIRTHDAY
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private Date   birthday;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.BIND_ACCT_WX
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String bindAcctWx;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column user.BIND_ACCT_WEIBO
     *
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    private String bindAcctWeibo;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.ID
     *
     * @return the value of user.ID
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.ID
     *
     * @param id the value for user.ID
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.GMT_MODIFIY
     *
     * @return the value of user.GMT_MODIFIY
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Date getGmtModifiy() {
        return gmtModifiy;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.GMT_MODIFIY
     *
     * @param gmtModifiy the value for user.GMT_MODIFIY
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setGmtModifiy(Date gmtModifiy) {
        this.gmtModifiy = gmtModifiy;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.GMT_CREATE
     *
     * @return the value of user.GMT_CREATE
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.GMT_CREATE
     *
     * @param gmtCreate the value for user.GMT_CREATE
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.MODIFIER
     *
     * @return the value of user.MODIFIER
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.MODIFIER
     *
     * @param modifier the value for user.MODIFIER
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.CREATOR
     *
     * @return the value of user.CREATOR
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.CREATOR
     *
     * @param creator the value for user.CREATOR
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.IS_DELETED
     *
     * @return the value of user.IS_DELETED
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.IS_DELETED
     *
     * @param isDeleted the value for user.IS_DELETED
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.LOGIN_ID
     *
     * @return the value of user.LOGIN_ID
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.LOGIN_ID
     *
     * @param loginId the value for user.LOGIN_ID
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.NICKNAME
     *
     * @return the value of user.NICKNAME
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.NICKNAME
     *
     * @param nickname the value for user.NICKNAME
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.PASSWORD
     *
     * @return the value of user.PASSWORD
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.PASSWORD
     *
     * @param password the value for user.PASSWORD
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.SEX
     *
     * @return the value of user.SEX
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.SEX
     *
     * @param sex the value for user.SEX
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.AVATAR
     *
     * @return the value of user.AVATAR
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.AVATAR
     *
     * @param avatar the value for user.AVATAR
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.INDUSTRY
     *
     * @return the value of user.INDUSTRY
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.INDUSTRY
     *
     * @param industry the value for user.INDUSTRY
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setIndustry(String industry) {
        this.industry = industry;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.REGION
     *
     * @return the value of user.REGION
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.REGION
     *
     * @param region the value for user.REGION
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.MEMO
     *
     * @return the value of user.MEMO
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.MEMO
     *
     * @param memo the value for user.MEMO
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.BIRTHDAY
     *
     * @return the value of user.BIRTHDAY
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.BIRTHDAY
     *
     * @param birthday the value for user.BIRTHDAY
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.BIND_ACCT_WX
     *
     * @return the value of user.BIND_ACCT_WX
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getBindAcctWx() {
        return bindAcctWx;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.BIND_ACCT_WX
     *
     * @param bindAcctWx the value for user.BIND_ACCT_WX
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setBindAcctWx(String bindAcctWx) {
        this.bindAcctWx = bindAcctWx;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column user.BIND_ACCT_WEIBO
     *
     * @return the value of user.BIND_ACCT_WEIBO
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public String getBindAcctWeibo() {
        return bindAcctWeibo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column user.BIND_ACCT_WEIBO
     *
     * @param bindAcctWeibo the value for user.BIND_ACCT_WEIBO
     * @mbggenerated Mon Apr 27 00:21:46 CST 2015
     */
    public void setBindAcctWeibo(String bindAcctWeibo) {
        this.bindAcctWeibo = bindAcctWeibo;
    }

}
