package com.yangqisport.dal.mapper;

import com.yangqisport.dal.dataobject.CommXAuthToken;
import com.yangqisport.dal.dataobject.CommXAuthTokenExample;
import com.yangqisport.framework.dal.BaseMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommXAuthTokenMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int countByExample(CommXAuthTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int deleteByExample(CommXAuthTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int insert(CommXAuthToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int insertSelective(CommXAuthToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    List<CommXAuthToken> selectByExample(CommXAuthTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    CommXAuthToken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CommXAuthToken record, @Param("example") CommXAuthTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CommXAuthToken record, @Param("example") CommXAuthTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommXAuthToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMM_X_AUTH_TOKEN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommXAuthToken record);
}