package com.yangqisport.dal.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public ActivityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyIsNull() {
            addCriterion("GMT_MODIFIY is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyIsNotNull() {
            addCriterion("GMT_MODIFIY is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyEqualTo(Date value) {
            addCriterion("GMT_MODIFIY =", value, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyNotEqualTo(Date value) {
            addCriterion("GMT_MODIFIY <>", value, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyGreaterThan(Date value) {
            addCriterion("GMT_MODIFIY >", value, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIY >=", value, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyLessThan(Date value) {
            addCriterion("GMT_MODIFIY <", value, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyLessThanOrEqualTo(Date value) {
            addCriterion("GMT_MODIFIY <=", value, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyIn(List<Date> values) {
            addCriterion("GMT_MODIFIY in", values, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyNotIn(List<Date> values) {
            addCriterion("GMT_MODIFIY not in", values, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIY between", value1, value2, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtModifiyNotBetween(Date value1, Date value2) {
            addCriterion("GMT_MODIFIY not between", value1, value2, "gmtModifiy");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("GMT_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("GMT_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("GMT_CREATE =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("GMT_CREATE <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("GMT_CREATE >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("GMT_CREATE <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("GMT_CREATE <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("GMT_CREATE in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("GMT_CREATE not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("GMT_CREATE not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andModifierIsNull() {
            addCriterion("MODIFIER is null");
            return (Criteria) this;
        }

        public Criteria andModifierIsNotNull() {
            addCriterion("MODIFIER is not null");
            return (Criteria) this;
        }

        public Criteria andModifierEqualTo(String value) {
            addCriterion("MODIFIER =", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotEqualTo(String value) {
            addCriterion("MODIFIER <>", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThan(String value) {
            addCriterion("MODIFIER >", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierGreaterThanOrEqualTo(String value) {
            addCriterion("MODIFIER >=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThan(String value) {
            addCriterion("MODIFIER <", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLessThanOrEqualTo(String value) {
            addCriterion("MODIFIER <=", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierLike(String value) {
            addCriterion("MODIFIER like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotLike(String value) {
            addCriterion("MODIFIER not like", value, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierIn(List<String> values) {
            addCriterion("MODIFIER in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotIn(List<String> values) {
            addCriterion("MODIFIER not in", values, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierBetween(String value1, String value2) {
            addCriterion("MODIFIER between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andModifierNotBetween(String value1, String value2) {
            addCriterion("MODIFIER not between", value1, value2, "modifier");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(String value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(String value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(String value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(String value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(String value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(String value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLike(String value) {
            addCriterion("CREATOR like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotLike(String value) {
            addCriterion("CREATOR not like", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<String> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<String> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(String value1, String value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(String value1, String value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("IS_DELETED is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("IS_DELETED is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(String value) {
            addCriterion("IS_DELETED =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(String value) {
            addCriterion("IS_DELETED <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(String value) {
            addCriterion("IS_DELETED >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(String value) {
            addCriterion("IS_DELETED >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(String value) {
            addCriterion("IS_DELETED <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(String value) {
            addCriterion("IS_DELETED <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLike(String value) {
            addCriterion("IS_DELETED like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotLike(String value) {
            addCriterion("IS_DELETED not like", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<String> values) {
            addCriterion("IS_DELETED in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<String> values) {
            addCriterion("IS_DELETED not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(String value1, String value2) {
            addCriterion("IS_DELETED between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(String value1, String value2) {
            addCriterion("IS_DELETED not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("TYPE like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("TYPE not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andGmtBeginIsNull() {
            addCriterion("GMT_BEGIN is null");
            return (Criteria) this;
        }

        public Criteria andGmtBeginIsNotNull() {
            addCriterion("GMT_BEGIN is not null");
            return (Criteria) this;
        }

        public Criteria andGmtBeginEqualTo(Date value) {
            addCriterion("GMT_BEGIN =", value, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginNotEqualTo(Date value) {
            addCriterion("GMT_BEGIN <>", value, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginGreaterThan(Date value) {
            addCriterion("GMT_BEGIN >", value, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginGreaterThanOrEqualTo(Date value) {
            addCriterion("GMT_BEGIN >=", value, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginLessThan(Date value) {
            addCriterion("GMT_BEGIN <", value, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginLessThanOrEqualTo(Date value) {
            addCriterion("GMT_BEGIN <=", value, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginIn(List<Date> values) {
            addCriterion("GMT_BEGIN in", values, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginNotIn(List<Date> values) {
            addCriterion("GMT_BEGIN not in", values, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginBetween(Date value1, Date value2) {
            addCriterion("GMT_BEGIN between", value1, value2, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andGmtBeginNotBetween(Date value1, Date value2) {
            addCriterion("GMT_BEGIN not between", value1, value2, "gmtBegin");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("LOCATION =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("LOCATION <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("LOCATION >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("LOCATION >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("LOCATION <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("LOCATION <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("LOCATION like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("LOCATION not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("LOCATION in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("LOCATION not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("LOCATION between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("LOCATION not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountIsNull() {
            addCriterion("JOIN_USER_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountIsNotNull() {
            addCriterion("JOIN_USER_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountEqualTo(Integer value) {
            addCriterion("JOIN_USER_COUNT =", value, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountNotEqualTo(Integer value) {
            addCriterion("JOIN_USER_COUNT <>", value, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountGreaterThan(Integer value) {
            addCriterion("JOIN_USER_COUNT >", value, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("JOIN_USER_COUNT >=", value, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountLessThan(Integer value) {
            addCriterion("JOIN_USER_COUNT <", value, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountLessThanOrEqualTo(Integer value) {
            addCriterion("JOIN_USER_COUNT <=", value, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountIn(List<Integer> values) {
            addCriterion("JOIN_USER_COUNT in", values, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountNotIn(List<Integer> values) {
            addCriterion("JOIN_USER_COUNT not in", values, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountBetween(Integer value1, Integer value2) {
            addCriterion("JOIN_USER_COUNT between", value1, value2, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andJoinUserCountNotBetween(Integer value1, Integer value2) {
            addCriterion("JOIN_USER_COUNT not between", value1, value2, "joinUserCount");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumIsNull() {
            addCriterion("MAX_JOIN_NUM is null");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumIsNotNull() {
            addCriterion("MAX_JOIN_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumEqualTo(Integer value) {
            addCriterion("MAX_JOIN_NUM =", value, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumNotEqualTo(Integer value) {
            addCriterion("MAX_JOIN_NUM <>", value, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumGreaterThan(Integer value) {
            addCriterion("MAX_JOIN_NUM >", value, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("MAX_JOIN_NUM >=", value, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumLessThan(Integer value) {
            addCriterion("MAX_JOIN_NUM <", value, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumLessThanOrEqualTo(Integer value) {
            addCriterion("MAX_JOIN_NUM <=", value, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumIn(List<Integer> values) {
            addCriterion("MAX_JOIN_NUM in", values, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumNotIn(List<Integer> values) {
            addCriterion("MAX_JOIN_NUM not in", values, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumBetween(Integer value1, Integer value2) {
            addCriterion("MAX_JOIN_NUM between", value1, value2, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andMaxJoinNumNotBetween(Integer value1, Integer value2) {
            addCriterion("MAX_JOIN_NUM not between", value1, value2, "maxJoinNum");
            return (Criteria) this;
        }

        public Criteria andCostTypeIsNull() {
            addCriterion("COST_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andCostTypeIsNotNull() {
            addCriterion("COST_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCostTypeEqualTo(String value) {
            addCriterion("COST_TYPE =", value, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeNotEqualTo(String value) {
            addCriterion("COST_TYPE <>", value, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeGreaterThan(String value) {
            addCriterion("COST_TYPE >", value, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeGreaterThanOrEqualTo(String value) {
            addCriterion("COST_TYPE >=", value, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeLessThan(String value) {
            addCriterion("COST_TYPE <", value, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeLessThanOrEqualTo(String value) {
            addCriterion("COST_TYPE <=", value, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeLike(String value) {
            addCriterion("COST_TYPE like", value, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeNotLike(String value) {
            addCriterion("COST_TYPE not like", value, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeIn(List<String> values) {
            addCriterion("COST_TYPE in", values, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeNotIn(List<String> values) {
            addCriterion("COST_TYPE not in", values, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeBetween(String value1, String value2) {
            addCriterion("COST_TYPE between", value1, value2, "costType");
            return (Criteria) this;
        }

        public Criteria andCostTypeNotBetween(String value1, String value2) {
            addCriterion("COST_TYPE not between", value1, value2, "costType");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("INTRODUCTION is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("INTRODUCTION is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("INTRODUCTION =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("INTRODUCTION <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("INTRODUCTION >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("INTRODUCTION >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("INTRODUCTION <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("INTRODUCTION <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("INTRODUCTION like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("INTRODUCTION not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("INTRODUCTION in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("INTRODUCTION not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("INTRODUCTION between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("INTRODUCTION not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andCoverImagesIsNull() {
            addCriterion("COVER_IMAGES is null");
            return (Criteria) this;
        }

        public Criteria andCoverImagesIsNotNull() {
            addCriterion("COVER_IMAGES is not null");
            return (Criteria) this;
        }

        public Criteria andCoverImagesEqualTo(String value) {
            addCriterion("COVER_IMAGES =", value, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesNotEqualTo(String value) {
            addCriterion("COVER_IMAGES <>", value, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesGreaterThan(String value) {
            addCriterion("COVER_IMAGES >", value, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesGreaterThanOrEqualTo(String value) {
            addCriterion("COVER_IMAGES >=", value, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesLessThan(String value) {
            addCriterion("COVER_IMAGES <", value, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesLessThanOrEqualTo(String value) {
            addCriterion("COVER_IMAGES <=", value, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesLike(String value) {
            addCriterion("COVER_IMAGES like", value, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesNotLike(String value) {
            addCriterion("COVER_IMAGES not like", value, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesIn(List<String> values) {
            addCriterion("COVER_IMAGES in", values, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesNotIn(List<String> values) {
            addCriterion("COVER_IMAGES not in", values, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesBetween(String value1, String value2) {
            addCriterion("COVER_IMAGES between", value1, value2, "coverImages");
            return (Criteria) this;
        }

        public Criteria andCoverImagesNotBetween(String value1, String value2) {
            addCriterion("COVER_IMAGES not between", value1, value2, "coverImages");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdIsNull() {
            addCriterion("PUBLISHER_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdIsNotNull() {
            addCriterion("PUBLISHER_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdEqualTo(Long value) {
            addCriterion("PUBLISHER_USER_ID =", value, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdNotEqualTo(Long value) {
            addCriterion("PUBLISHER_USER_ID <>", value, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdGreaterThan(Long value) {
            addCriterion("PUBLISHER_USER_ID >", value, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PUBLISHER_USER_ID >=", value, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdLessThan(Long value) {
            addCriterion("PUBLISHER_USER_ID <", value, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdLessThanOrEqualTo(Long value) {
            addCriterion("PUBLISHER_USER_ID <=", value, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdIn(List<Long> values) {
            addCriterion("PUBLISHER_USER_ID in", values, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdNotIn(List<Long> values) {
            addCriterion("PUBLISHER_USER_ID not in", values, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdBetween(Long value1, Long value2) {
            addCriterion("PUBLISHER_USER_ID between", value1, value2, "publisherUserId");
            return (Criteria) this;
        }

        public Criteria andPublisherUserIdNotBetween(Long value1, Long value2) {
            addCriterion("PUBLISHER_USER_ID not between", value1, value2, "publisherUserId");
            return (Criteria) this;
        }
    }

    /**
     * ACTIVITY
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTIVITY
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ACTIVITY
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}